[project]
name = "jbtsdk"
version = "0.0.1"
authors = [
  { name="Thales Araújo", email="thales@jabuti.ai" },
  { name="Cecilio Cosac", email="cecilioc@jabuti.ai" },
]
dependencies = ["requests"]
description = "SDK for Jabuti Platform"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://github.com/jabuti-ai/jabuti-sdk"
Issues = "https://github.com/jabuti-ai/jabuti-sdk/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

